# if you update this file, please consider updating Vagrantfile too

language: cpp

env:
  global:
    - JOBS=4
    - SHADOW_BUILD_DIR=/tmp/shadow_build_dir
    - CODESIGN=nocodesign
    - secure: FRk3fzUGN4Befc3y5BRiIKjHL4CKH9QxnWEKSMdjpfdQAtmJL5sfwQchvqO8qeyPMLBMjBjys24PF8cJivCZ7TVTfLuz5bvL+4ZKjkN8MnZBPAEASB/lbEVmXJIqY1w6osf9Gk89yA31Z6algcjNd2d3OaxjodXvveh/dUKkaFQbtTAE15AYzDabtgcWq9fe/9M7sIEo6iHiPMmU4OusQrLgvHdTwxg9CcLN6s/IC5Lp7pUoTFHFmsa/cBWeEOMypdEvJArw63v7VqQ0LVAXpwchudjwmkCu0rhP8aOtmhm1YnxFfyGnf1dx4t57wAqbkUTYGDy+TIqePBJ+u2dSkpm8I3gzysdDSLYt2Jz9pY8RZKxHSgR4pGJOL3SrJeXdxRMwAEyQYYMb3Z+BvZ4pbBQq7o2VGQDwNd4cjqSFUazTxaENYG+a4MfYN+jMbscFxZ0r3RWS+XBbUhjsaiuRhSj9x70zkv4Z8PXucDyXWlYQ+y36I1M1xFMbsUCQgYH111y1HOHXZxiXe5a7aUSHddg/9nFLv6buqpa2zKjNcJ41fpT+RH38ntqyR+Lr88hQcBvOGuXLci2XahHoTmbFYWuglv69WT8u5R8NQ+ok2OqrE9oim20kEvyWyo2uff5l1ivgLHBMmpxzWGxor6U2gqadmLWLObO8i6rQO6zPWBI=

jobs:
    fast_finish: true
    include:
        - stage: "Build"
          name: "Linux Installer"
          os: linux
          dist: bionic
          env: SPEC=linux-g++-64 CONFIG=installer
          sudo: required
#        - stage: "Build"
#          name: "Linux Debug"
#          os: linux
#          dist: bionic
#          env: SPEC=linux-g++-64 CONFIG=debug
#          services: xvfb
#          sudo: required
        - stage: "Build"
          name: "Android 32 bit"
          dist: xenial
          language: android
          env: SPEC=android-clang CONFIG=installer BITNESS=32 GSTREAMER_NAME=armv7
          sudo: false
        - stage: "Build"
          name: "Android 64 bit"
          dist: xenial
          language: android
          env: SPEC=android-clang CONFIG=installer BITNESS=64 GSTREAMER_NAME=arm64
          sudo: false
#        - stage: "Build"
#          name: "OSX Installer"
#          os: osx
#          osx_image: xcode11.3
#          env: SPEC=macx-clang CONFIG=installer
#          sudo: required
#        - stage: "Google Play Upload"
#          name: "Google Play Upload"
#          dist: trusty
#          language: android
#          env: SPEC=google-play-upload
#          sudo: false
          before_install: echo "before install"
          install: echo "install"
          before_script: echo "before script"
          before_deploy: echo "before deploy"
          after_deploy: echo "after deploy"
          script: echo "Google Play Upload"
        
# iOS build needs updating Qt to > 5.10
#        - os: osx
#          osx_image: xcode9.2
#          env: SPEC=macx-ios-clang CONFIG=release
#          sudo: false
# OSX builds pared back to installer only since travis sucks so bad we can't afford more than one'
#        - os: osx
#          osx_image: xcode10.1
#          env: SPEC=macx-clang CONFIG=debug
#          sudo: required

android:
  components:
    - android-29
    - build-tools-25.0.3
    - platform-tools

addons:
  apt:
    packages:
    - speech-dispatcher
    - libgstreamer-plugins-base1.0-dev
    - libgstreamer1.0-0:amd64
    - libgstreamer1.0-dev
    - libudev-dev
    - wget

before_install:
  # fetch entire git repo to properly determine the version
  - cd ${TRAVIS_BUILD_DIR}
  - git fetch --unshallow
  - git fetch --all --tags

  # compile threads
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
        export JOBS=$((`cat /proc/cpuinfo | grep -c ^processor`+1));
    elif [ "${TRAVIS_OS_NAME}" = "osx" ]; then
        export JOBS=$((`sysctl -n hw.ncpu`+1));
    fi

  # Linux needs sdl2 but not android
  - if [ "${SPEC}" = "linux-g++-64" ]; then
        sudo apt-get install -y libsdl2-dev libxkbcommon-x11-0;
    fi

install:
  # linux dependencies: qt
  - if [ "${SPEC}" = "linux-g++-64" ]; then
        wget --quiet https://s3-us-west-2.amazonaws.com/qgroundcontrol/dependencies/Qt5.12.6-gcc_64-min.tar.bz2 &&
        tar jxf Qt5.12.6-gcc_64-min.tar.bz2 -C /tmp &&
        export PATH=/tmp/Qt5.12-gcc_64/5.12.6/gcc_64/bin:$PATH
        ;
    fi

  # android dependencies: qt, gstreamer, android-ndk
  - if [ "${SPEC}" = "android-clang" ]; then
        wget --quiet https://qgroundcontrol.s3-us-west-2.amazonaws.com/dependencies/gstreamer-1.0-android-universal-1.18.1.tar.xz &&
        mkdir gstreamer-1.0-android-universal-1.18.1 &&
        tar xf gstreamer-1.0-android-universal-1.18.1.tar.xz -C gstreamer-1.0-android-universal-1.18.1 &&
        wget --quiet https://dl.google.com/android/repository/android-ndk-r20-linux-x86_64.zip &&
        unzip android-ndk-r20-linux-x86_64.zip > /dev/null &&
        export ANDROID_NDK_ROOT=`pwd`/android-ndk-r20 &&
        export ANDROID_SDK_ROOT=/usr/local/android-sdk &&
        export PATH=`pwd`/android-ndk-r20:$PATH
        ;
    fi

  - if [[ "${SPEC}" = "android-clang" && "${BITNESS}" = "64" ]]; then
        wget --quiet https://s3-us-west-2.amazonaws.com/qgroundcontrol/dependencies/Qt5.12.6-android_arm64_v8a-min.tar.bz2 &&
        tar jxf Qt5.12.6-android_arm64_v8a-min.tar.bz2 -C /tmp &&
        export PATH=/tmp/Qt5.12-android_arm64_v8a/5.12.6/android_arm64_v8a/bin:$PATH
        ;
    fi

  - if [[ "${SPEC}" = "android-clang" && "${BITNESS}" = "32" ]]; then
        wget --quiet https://s3-us-west-2.amazonaws.com/qgroundcontrol/dependencies/Qt5.12.6-android_armv7-min.tar.bz2 &&
        tar jxf Qt5.12.6-android_armv7-min.tar.bz2 -C /tmp &&
        export PATH=/tmp/Qt5.12-android_armv7/5.12.6/android_armv7/bin:$PATH
        ;
    fi

  # osx dependencies: qt (master builds only: gstreamer, gstreamer-devel)
  - if [ "${SPEC}" = "macx-clang" ]; then
        wget --quiet https://s3-us-west-2.amazonaws.com/qgroundcontrol/dependencies/Qt5.12.6-clang_64-min.tar.bz2 &&
        tar jxf Qt5.12.6-clang_64-min.tar.bz2 -C /tmp
        ;
    fi

  - if [[ "${SPEC}" = "macx-clang" ]]; then
        wget --quiet https://qgroundcontrol.s3-us-west-2.amazonaws.com/dependencies/gstreamer-osx-1.18.1.tar.bz2 &&
        sudo tar zxf gstreamer-osx-1.18.1.tar.bz2 -C /Library/Frameworks
        ;
    fi

  - if [ "${SPEC}" = "macx-clang" ]; then
        export QT_DIR=Qt5.12-clang_64/5.12.6/clang_64 &&
        export QT_QPA_PLATFORM_PLUGIN_PATH=/tmp/$QT_DIR/plugins &&
        export QML2_IMPORT_PATH=/tmp/$QT_DIR/qml &&
        export PATH=/tmp/$QT_DIR/bin:$PATH
        ;
    fi

  # ios dependencies: qt
  - if [ "${SPEC}" = "macx-ios-clang" ]; then
        wget --quiet https://s3-us-west-2.amazonaws.com/qgroundcontrol/dependencies/Qt5.9.3-ios-min.tar.bz2
        ;
    fi
  - if [ "${SPEC}" = "macx-ios-clang" ]; then
        tar jxf Qt5.9.3-ios-min.tar.bz2 -C /tmp &&
        export IOS_CCACHE_CC=`/usr/bin/xcrun -sdk iphoneos -find clang` &&
        export IOS_CCACHE_CXX=`/usr/bin/xcrun -sdk iphoneos -find clang++` &&
        export PATH=/tmp/Qt5.9-ios/5.9.3/ios/bin:$PATH
        ;
    fi

before_script:
  - cd ${TRAVIS_BUILD_DIR}

  # switch android config from installer to release if the android storepass isn't available
  - if [[ "${SPEC}" = "android-clang" && "${CONFIG}" = "installer" && -z ${ANDROID_STOREPASS} ]]; then
        export CONFIG=release;
    fi

  # insert QGC version in AndroidManifest.xml
  #- if [ "${SPEC}" = "android-clang" ]; then
  #      git remote set-branches origin 'Stable_V4.1' &&
  #      git fetch --tags origin Stable_V4.1 &&
  #      ./tools/update_android_version.sh ${BITNESS} ${TRAVIS_BRANCH};
  #  fi
    
  # Install signing cert into OSX keychain
  - if [[ "${SPEC}" = "macx-clang" && "${TRAVIS_PULL_REQUEST}" = "false" ]]; then
        export CODESIGN=codesign;
    fi
  - if [[ "${SPEC}" = "macx-clang" && "${TRAVIS_PULL_REQUEST}" = "false" ]]; then
        openssl aes-256-cbc -K $MAC_CERT_KEY -iv $MAC_CERT_IV -in deploy/MacCertificates.p12.enc -out deploy/MacCertificates.p12 -d;
    fi
  - if [[ "${SPEC}" = "macx-clang" && "${TRAVIS_PULL_REQUEST}" = "false" ]]; then
        source deploy/MacImportCert.sh;
    fi

script:
  # run qmake
  - mkdir ${SHADOW_BUILD_DIR} && cd ${SHADOW_BUILD_DIR}
  - if [ "${TRAVIS_TAG}" ]; then
        echo "Stable build" &&
        export STABLE_OR_DAILY=StableBuild;
    else
        echo "Daily build" &&
        export STABLE_OR_DAILY=DailyBuild;
    fi
  - qmake -r ${TRAVIS_BUILD_DIR}/qgroundcontrol.pro CONFIG+=${CONFIG} CONFIG+=${STABLE_OR_DAILY} CONFIG+=${CODESIGN} -spec ${SPEC};

  # compile
  - if [ "${SPEC}" != "macx-ios-clang" ]; then
        make -j$JOBS;
    else
        xcodebuild -IDEBuildOperationMaxNumberOfConcurrentCompileTasks=$JOBS -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c && $(exit ${PIPESTATUS[0]});
    fi
  #- ccache -s

  # unit tests linux
  - if [[ "${SPEC}" = "linux-g++-64" && "${CONFIG}" = "debug" ]]; then
    	mkdir -p ~/.config/QtProject/ &&
        cp ${TRAVIS_BUILD_DIR}/test/qtlogging.ini ~/.config/QtProject/ &&
        export QT_FATAL_WARNINGS=1 &&
        ./staging/qgroundcontrol-start.sh --unittest;
    fi


after_success:
#  # This is only used to upload android builds to Google Play
#  - cd ${TRAVIS_BUILD_DIR}
#  - if [ "${TRAVIS_TAG}" ]; then
#        GOOGLE_PLAY_PKG=org.mavlink.qgroundcontrol;
#    elif [ "${TRAVIS_BRANCH}" = "master" ]; then
#        GOOGLE_PLAY_PKG=org.mavlink.qgroundcontrolbeta;
#    else
#        GOOGLE_PLAY_PKG=none;
#    fi
#  - if [[ "${SPEC}" = "google-play-upload" && "${TRAVIS_PULL_REQUEST}" = "false" && "${GOOGLE_PLAY_PKG}" != "none" ]]; then
#        wget --quiet https://s3-us-west-2.amazonaws.com/qgroundcontrol/builds/${TRAVIS_BRANCH}/QGroundControl32.apk &&
#        wget --quiet https://s3-us-west-2.amazonaws.com/qgroundcontrol/builds/${TRAVIS_BRANCH}/QGroundControl64.apk &&
#        pip install --user --upgrade oauth2client &&
#        pip install --user google-api-python-client pyopenssl ndg-httpsclient pyasn1 &&
#        openssl aes-256-cbc -K $encrypted_25db6eb7c3fd_key -iv $encrypted_25db6eb7c3fd_iv -in android/Google_Play_Android_Developer-4432a3c4f5d1.json.enc -out android/Google_Play_Android_Developer-4432a3c4f5d1.json -d &&
#        ./deploy/GooglePlayUpload.py ${GOOGLE_PLAY_PKG};
#    fi

before_deploy:
  # create linux appimage
  - cd ${TRAVIS_BUILD_DIR}
  - if [[ "${SPEC}" = "linux-g++-64" && "${CONFIG}" = "installer" ]]; then
        ./deploy/create_linux_appimage.sh ${TRAVIS_BUILD_DIR} ${SHADOW_BUILD_DIR}/staging ${SHADOW_BUILD_DIR}/package;
    fi

deploy:
#  # deploy installers to s3 builds/ if on a branch
#  - provider: s3
#    edge: true # Use V2 provider to work around V1 bug
#    access_key_id: AKIAIVORNALE7NHD3T6Q
#    secret_access_key:
#      secure: BsLXeXUPsCJdX4tawrDnO8OFK5Hk4kzlDTiyH93En6TbjUargVAWDMcHVj7TUhr7+3Tao1W1zb0G4SJe9kHv+jrky0yE72KvoG3YAON0VXWKizxBAKkgHE2RxSTNAwDeKbi2G6YJfNDescBBfX7zEohShdXglQu7CGaUQKRaiI4=
#    bucket: qgroundcontrol
#    local_dir: ${SHADOW_BUILD_DIR}/package
#    upload-dir: builds/${TRAVIS_BRANCH}
#    acl: public_read
#    region: us-west-2
#    skip_cleanup: true
#    on:
#      all_branches: true
#      condition: $CONFIG = installer

#  # deploy tagged installers to s3 latest/
#  - provider: s3
#    edge: true # Use V2 provider to work around V1 bug
#    access_key_id: AKIAIVORNALE7NHD3T6Q
#    secret_access_key:
#      secure: BsLXeXUPsCJdX4tawrDnO8OFK5Hk4kzlDTiyH93En6TbjUargVAWDMcHVj7TUhr7+3Tao1W1zb0G4SJe9kHv+jrky0yE72KvoG3YAON0VXWKizxBAKkgHE2RxSTNAwDeKbi2G6YJfNDescBBfX7zEohShdXglQu7CGaUQKRaiI4=
#    bucket: qgroundcontrol
#    local_dir: ${SHADOW_BUILD_DIR}/package
#    upload-dir: latest
#    acl: public_read
#    region: us-west-2
#    skip_cleanup: true
#    on:
#      tags: true
#      condition: $CONFIG = installer

#  # deploy tagged installers to s3 version folder
#  - provider: s3
#    edge: true # Use V2 provider to work around V1 bug
#    access_key_id: AKIAIVORNALE7NHD3T6Q
#    secret_access_key:
#      secure: BsLXeXUPsCJdX4tawrDnO8OFK5Hk4kzlDTiyH93En6TbjUargVAWDMcHVj7TUhr7+3Tao1W1zb0G4SJe9kHv+jrky0yE72KvoG3YAON0VXWKizxBAKkgHE2RxSTNAwDeKbi2G6YJfNDescBBfX7zEohShdXglQu7CGaUQKRaiI4=
#    bucket: qgroundcontrol
#    local_dir: ${SHADOW_BUILD_DIR}/package
#    upload-dir: ${TRAVIS_BRANCH}
#    acl: public_read
#    region: us-west-2
#    skip_cleanup: true
#    on:
#      tags: true
#      condition: $CONFIG = installer

 # deploy installers to Github releases if on a tag
  - provider: releases
    edge: true # Use V2 provider to work around V1 bug
    api-key:
      secure: l/3Xl7nHkDNVBJCFMYnVtNwU36UYwRKbzx2rAtOQSSmKYhDa4WkbN5p5LhvZ4O1z/0FYlvkar7whafTqlaVFPPHK6juC1Gbk9qBIh1mEPMY7E8fe2C0XYrzwtp6XT54xcsP9F5cD/W8fZKzzhX0uHqQj0OdYxJ2EEM4o3E7G+AnX9TVyCUwNc6ekKddHEPosNT/YyVb06VLpM0+IMM5NxqgjMJESA99/gq1QcsYN0LPUrBHq99mIcm4qmA+H0g/P/z7eFc1UfIOb9/CfkCnAwUBdNnb9gagnIXCOYpuqqFCVgQZ6dI4pu+BZzS8qxNdGhhtZ1UvjPNQSDkwPGFA1+N43r7X5+ROwv8oT8ZwTc9LUvgG2wzNj9ldrwYyvNeiNJJBBQvvwP22mhkd99ufVfaCJfOzzdBdGSUVxjoGBaMljif2H18XZJeLAtMEqd5oD/t8SVZZvzL5RldakCQCSJlz1LO0uy7C6C3zvgKdr8o52YCVGt3ZTVCU90P8mPLe5M2tmvUgxtW+om3HHLYWiryjo8IjfBOAK4evHFkry4n2dKPwWYFKQd73zlUADva8DDxwwfx8QDMnmQuqEWwqwpLzZCQuyPHU4G0s0m2eov8dLonahlV8vvt5HgIIVOWfXy40rdp6du6R9TkpFI9kadQftID+lcqpiR4hjItmsXq0=
    file_glob: true
    file:
      - ${SHADOW_BUILD_DIR}/qgc-app/package/qgroundcontrol.*
      - ${SHADOW_BUILD_DIR}/qgc-app/package/QGroundControl.*
    skip_cleanup: true
    on:
      tags: true
      condition: $CONFIG = installer
      condition: $SPEC != macx-clang # GitHub OSX deploy broken due to travis problem

#notifications:
#  webhooks:
#    urls:
#      - https://webhooks.gitter.im/e/60b033428ae9dc715662
#    on_success: change
#    on_failure: always
#    on_start: never
